version: "3.9"

services:
  influxdb:
    image: influxdb:2.1.1
    ports:
    - 8086:8086
    restart: always
  influxdb-setup:
    image: influxdb:2.1.1
    restart: "no"
    depends_on:
    - influxdb
    links:
    - "influxdb:influx"
    volumes:
    - influx_token:/influx_token
    command: |
      /bin/bash -c "
      for i in {1..3}; do
      echo 'Attempting to setup influxdb...';
      influx setup \
      --host http://influx:8086 \
      --org waggle \
      --bucket waggle \
      --username waggle \
      --password wagglewaggle \
      --force;
      influx auth create \
      --user waggle \
      --org waggle \
      --hide-headers \
      --write-buckets \
      --read-buckets \
      -d waggle-read-write-token | awk '{print $$3}' > /influx_token/token && cat /influx_token/token && break;
      sleep 1;
      done"
volumes:
  influx_token: