name: Create Docker image for release

on:
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Test package
        run: python3 -m unittest discover tests
  push_to_registry:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx for multi-arch builds
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: waggle/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}